/**
 * Created by yhg97p on 2016/1/5.
 */
var finicialApp = angular.module("Finicial",[
    "ui.router","ngRoute","ngAnimate","ngCookies","SigninCtrl","FirstPage","IndividualCtrl","TestCtrl","BillsCtrl","ChartsCtrl","SettingCtrl","FinicialCtrl"
]);

finicialApp.config(function($stateProvider,$urlRouterProvider){
    $urlRouterProvider.otherwise('/signin');
    $stateProvider
//        测试
        .state('test',{
            url:'/test',
            templateUrl:'test.html',
            //controller:'TestController'
        })
        .state('manage',{
            url:'/manage',
            templateUrl:''
        })
//      登录，注册，找回密码
        .state('signin',{
            url:'/signin',
            templateUrl:'main/signin.html',
            controller:'SigninController'
         })
//      个人管理系统界面
        .state('individual',{
            url:'/individual',
            views:{
                '':{
                    templateUrl:'main/individualHomepage.html',
                    //controller:'individualController',
                },
               'mainbody@individual':{
                   templateUrl:'part/firstpage.html'
               }
            }
        })
//      首页
        .state('individual.firstpage',{
            url:'/firstpage',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/firstpage.html',
                    //controller:'firstpageController'
                }
            }
        })
//     记账
        .state('individual.bills',{
            url:'/bills01',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/bills01.html',
                    controller:'bills01Controller'
                }
            }
        })
        .state('individual.bills01',{
            url:'/bills01',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/bills01.html',
                    controller:'bills01Controller'
                }
            }
        })
        .state('individual.bills02',{
            url:'/bills02',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/bills02.html',
                    controller:'bills02Controller'
                }
            }
        })
//      报表
        .state('individual.form01',{
            url:'/form01',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/form01.html',
                }
            }
        })
        .state('individual.form02',{
            url:'/form02',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/form02.html',
                    controller:'form02Controller',
                }
            }
        })
        .state('individual.form03',{
            url:'/form03',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/form03.html',
                }
            }
        })
        .state('individual.form04',{
            url:'/form04',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/form04.html',
                }
            }
        })
        .state('individual.form05',{
            url:'/form05',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/form05.html',
                }
            }
        })
//      账户
        .state('individual.account01',{
            url:'/account01',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/account01.html',
                }
            }
        })
        .state('individual.account02',{
            url:'/account02',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/account02.html',
                }
            }
        })
        .state('individual.account03',{
            url:'/account03',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/account03.html',
                }
            }
        })
        .state('individual.account04',{
            url:'/account04',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/account04.html',
                }
            }
        })
        .state('individual.account05',{
            url:'/account05',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/account05.html',
                }
            }
        })
//      设置
        .state('individual.setting01',{
            url:'/setting01',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/setting01.html',
                }
            }
        })
        .state('individual.setting02',{
            url:'/setting02',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/setting02.html',
                }
            }
        })
        .state('individual.setting03',{
            url:'/setting03',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/setting03.html',
                }
            }
        })
        .state('individual.setting04',{
            url:'/setting04',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/setting04.html',
                }
            }
        })
        .state('individual.setting05',{
            url:'/setting05',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/setting05.html',
                }
            }
        })
        .state('individual.setting06',{
            url:'/setting06',
            views:{
                'mainbody@individual':{
                    templateUrl:'part/setting06.html',
                }
            }
        })
});
